title: Klangkunst Manufaktur e.V.
email: 
description:
# baseurl: ""
url: "https://www.klangkunstmanufaktur.de" # the base hostname & protocol for your site, e.g. http://example.com
nav_title_1: Klangkunst
nav_title_2: Manufaktur
navs:
  - text: Aktuelles
    link: "index.html"
  - text: Geschichte
    link: "geschichte.html"
  - text: Dirigent
    link: "dirigent.html"
  - text: Galerie 
posters:
  - src: "src/plakate/Klangkunst Plakat 2018-I.png"
    title: KlangkunstManufaktur Projekt I - 2018
  - src: "src/plakate/Klangkunst Plakat 2018-II.png"
    title: KlangkunstManufaktur Projekt II - 2018
  - src: "src/plakate/Klangkunst Plakat 2019-I.png"
    title: KlangkunstManufaktur Projekt I - 2019
  - src: "src/plakate/Klangkunst Plakat 2019-II.png"
    title: KlangkunstManufaktur Projekt II - 2019
  - src: "src/plakate/Klangkunst Plakat 2020-II.png"
    title: KlangkunstManufaktur Projekt II - 2020
  - src: "src/plakate/Klangkunst Plakat 2021-II.png"
    title: KlangkunstManufaktur Projekt II - 2021
  - src: "src/plakate/Klangkunst Plakat 2022-I.png"
    title: KlangkunstManufaktur Projekt I - 2022
  - src: "src/plakate/Klangkunst Plakat 2022-II.png"
    title: KlangkunstManufaktur Projekt II - 2022
  - src: "src/plakate/Klangkunst Plakat 2023-I.png"
    title: KlangkunstManufaktur Projekt I - 2023
  - src: "src/plakate/Klangkunst Plakat 2023-II.png"
    title: KlangkunstManufaktur Projekt II - 2023
  - src: "src/plakate/Klangkunst Plakat 2024-I.png"
    title: KlangkunstManufaktur Projekt I - 2024
actual_poster:
  - src: "src/plakate/Klangkunst Plakat 2024-II.png"
    title: KlangkunstManufaktur Projekt II - 2024
footer_elements:
  - name: Impressum
    link: "impressum.html"
  - name: Datenschutz
    link: "datenschutz.html"
  