title: Klangkunst Manufaktur e.V.
email: 
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
nav_title: 
  text: Klangkunst Manufaktur
  link: "index.html"
navs:
  - text: Über uns
    link: "index.html"
  - text: Geschichte
    link: "geschichte.html"
  - text: Dirigent
    link: "dirigent.html"
  - text: Aktuelles
  - text: Galerie
posters:
  - src: "src/plakate/Klangkunst Plakat 2017.png"
    title: Projekt 1 - Ensemble Klangkunst - 2017
  - src: "/src/plakate/Klangkunst Plakat 2018-I.png"
    title: KlangkunstManufaktur Projekt I - 2018
  - src: "/src/plakate/Klangkunst Plakat 2018-II.png"
    title: KlangkunstManufaktur Projekt II - 2018
  - src: "/src/plakate/Klangkunst Plakat 2019-I.png"
    title: KlangkunstManufaktur Projekt I - 2019
  - src: "/src/plakate/Klangkunst Plakat 2019-II.png"
    title: KlangkunstManufaktur Projekt II - 2019
  - src: "/src/plakate/Klangkunst Plakat 2020-II.png"
    title: KlangkunstManufaktur Projekt II - 2020
  - src: "/src/plakate/Klangkunst Plakat 2021-II.png"
    title: KlangkunstManufaktur Projekt II - 2021
  - src: "/src/plakate/Klangkunst Plakat 2022-I.png"
    title: KlangkunstManufaktur Projekt I - 2022
  - src: "/src/plakate/Klangkunst Plakat 2022-II.png"
    title: KlangkunstManufaktur Projekt II - 2022
  - src: "/src/plakate/Klangkunst Plakat 2023-I.png"
    title: KlangkunstManufaktur Projekt I - 2023
  - src: "/src/plakate/Klangkunst Plakat 2023-II.png"
    title: KlangkunstManufaktur Projekt II - 2023
footer_elements:
  - name: Kontakt
  - name: Impressum
  - name: Datenschutz
  